### ISSUE TITLE
Does TPAT support grid_sample?

### ISSUE THREAD

**Issue by dingjingzhen** [Tencent/TPAT#14]
Does TPAT support grid_sample, and if not, when will it support it?

**Comment by buptqq** [comment]
You can find all of supported operators in [Operators](https://github.com/Tencent/TPAT/blob/main/docs/Operators.md).
GridSample is not supported now.
It is expected to take at least one month to support GridSample, if it is done in advance we will let you know here

**Comment by buptqq** [comment]
hi @dingjingzhen , We have supported grid-sample operator.Pleace try it:
https://github.com/Tencent/TPAT/tree/dev
Don't forget update submodule

**Comment by buptqq** [comment]
> Does TPAT support grid_sample, and if not, when will it support it?

hi @dingjingzhen , We have supported grid-sample operator.Pleace try it:
https://github.com/Tencent/TPAT/tree/dev
Don't forget update submodule:
https://github.com/Tencent/BlazerML-tvm/tree/9dd9e33509137ae4011c0524d5312c41a6b82182
