### ISSUE TITLE
Support for dynamic shape ?

### ISSUE THREAD

**Issue by sleepwalker2017** [Tencent/TPAT#22]
Does it support Dynamic shape kernel generation?

**Comment by zhuwenxi** [comment]
Currently we do NOT have a full dynamic shape generation support, since TVM haven't support it yet, sorry.

Nevertheless, If you want dynamic batch size kernel generation, TPAT already support it. Feel free to have a try.

**Comment by sleepwalker2017** [comment]
thank you
