### ISSUE TITLE
When will dynamic BatchSize be supported

### ISSUE THREAD

**Issue by zhaohb** [Tencent/TPAT#6]
When will dynamic BatchSize be supported？

**Comment by buptqq** [comment]
Expected in late May or early June 2022, The function has been developed and we are now testing.^_^

**Comment by zhaohb** [comment]
Looking forward to it

**Comment by DatCanCode** [comment]
Can't wait anymore for dynamic BatchSize. I'm so excited about this project

**Comment by buptqq** [comment]
> Can't wait anymore for dynamic BatchSize. I'm so excited about this project

TPAT already support dynamic batch，you can try it.
